#!/usr/bin/env python
#-*- coding:utf-8 -*-

import sys
import utils
from package import EastwindPackage
from pkgmanager.manager import EastwindPkgManager

class Eastwind:
    """ Command line interface for eastwin """

    def __init__(self):
        self.pkg_manager = EastwindPkgManager()
        self.handle(sys.argv[1], sys.argv[2:])

    def handle(self, action, arg):
        if action == 'pack':
            pkg = EastwindPackage(arg[0])
            pkg.pack(arg[1])
        elif action == 'unpack':
            pkg = EastwindPackage.extract(arg[0])
            pkg.unpack()
        elif action == 'install':
            self.install(arg)
        elif action == 'remove':
            self.remove(arg)
        else:
            pass

    def install(self, pkgs):
        if 0 == self.pkg_manager.install_interactive(pkgs):
            try:
                with open(utils.app_path('installed'), 'r') as f:
                    lines = f.readlines()
            except IOError:
                lines = []

            for pkg in pkgs:
                pkg = pkg.rstrip('\n') + '\n'
                if not pkg in lines:
                    lines.append(pkg)
            lines.sort()

            with open(utils.app_path('installed'), 'w') as f:
                for pkg in lines:
                    f.write(pkg)

    def remove(self, pkgs):
        if 0 == self.pkg_manager.purge_interactive(pkgs):
            try:
                with open(utils.app_path('installed'), 'r') as f:
                    lines = f.readlines()
            except IOError:
                lines = []

            for pkg in pkgs:
                pkg = pkg.rstrip('\n') + '\n'
                if pkg in lines:
                    lines.remove(pkg)

            with open(utils.app_path('installed'), 'w') as f:
                for pkg in lines:
                    f.write(pkg)


if __name__ == "__main__":
    Eastwind()

