#!/bin/bash

owd=`pwd`
PKG_DIR=${owd}/build
package=${owd##/*/}

mkdir -p $PKG_DIR

if [ -e configure.ac ]; then
  version=`sed -n 's/AC_INIT([^,]*, \[\([a-zA-Z0-9.~\-]*\)\], .*/\1/p' configure.ac`
elif [ -e setup.py ]; then
  version=`sed -n "s/.*version = '\(.*\)'.*/\1/p" setup.py`
fi

if [ "$1" == "clean" ]; then
  rm -rf $PKG_DIR/*
  exit 0
fi

echo "Package: $package"
echo "Version: $version"

cd ..
cp -r $package /tmp/$package-$version
rm -rf /tmp/$package-$version/dev
rm -rf /tmp/$package-$version/.git
mv /tmp/$package-$version $PKG_DIR
cd $PKG_DIR

if [ "$1" == "sdist" ]; then
  tar -zcf ${package}-$version.tar.gz $package-$version
  exit 0
else
  tar -zcf ${package}_$version.orig.tar.gz $package-$version
fi

cd $package-$version

cp $owd/debian/rules $owd/debian/control $owd/debian/copyright $owd/debian/postinst $owd/debian/prerm $owd/debian/changelog debian

if [ "$1" == "deb" ] || [ -z "$1" ]; then
  dpkg-buildpackage -rfakeroot
elif [ "$1" == "ppa" ]; then
  debuild -S
fi

